[versions]
jdk = "21"
kotlin = "1.9.23"
ksp = "1.9.22-1.0.18"
kotlinx-coroutines-core = "1.8.0"
hamcrest-core = "2.2"
hamcrest-date = "2.0.8"
java-vavr = "0.10.4"
kotlin-vavr = "0.10.2"
assertj-vavr = "0.4.3"
typeTools = "0.6.3"
moshi = "2.0.0-SNAPSHOT"
moshix = "0.26.0-SNAPSHOT"
http4k = "5.13.9.0"
arrow = "1.2.3"
klaxon = "5.6"
spotbugs = "6.0.8"
lombok-gradle = "8.6"
reflection-util = "2.15.0"
guava = "33.0.0-jre"
jackson-databind = "2.16.1"
apache-commons-lang3 = "3.14.0"
apache-commons-collections4 = "4.4"
vador = "1.1.0"
revoman = "0.33.8"
graal = "23.1.2"
graal-js = "23.0.3"
immutables = "2.10.1"
mockito = "5.11.0"
state-machine = "0.2.0"
spring = "6.1.4"
spring-dependency-management = "1.1.4"
spring-boot = "3.2.3"
okio = "3.8.0"
rabbitmq-client = "5.20.0"
kotlin-logging = "6.0.3"
pprint = "2.0.2"
dependency-analysis = "1.30.0"

# Common dependencies
junit = "5.10.2"
kover = "0.7.6"
kotest = "5.8.0"
assertj-core = "3.25.3"
truth = "1.4.2"
detekt = "1.23.5"
spotless = "6.25.0"
apache-log4j = "2.23.0"
testLogger = "4.0.0"
gradle-doctor = "0.9.2"
jetbrains-annotations = "24.1.0"

[libraries]
hamcrest-core = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest-core" }
hamcrest-date = { module = "org.exparity:hamcrest-date", version.ref = "hamcrest-date" }
java-vavr = { module = "io.vavr:vavr", version.ref = "java-vavr" }
kotlin-vavr = { module = "io.vavr:vavr-kotlin", version.ref = "kotlin-vavr" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
typeTools = { module = "net.jodah:typetools", version.ref = "typeTools" }
reflection-util = { module = "de.cronn:reflection-util", version.ref = "reflection-util" }
testLogger-gradle = { module = "com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin", version.ref = "testLogger" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runnerJUnit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
assertj-vavr = { module = "org.assertj:assertj-vavr", version.ref = "assertj-vavr" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang3" }
apache-commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "apache-commons-collections4" }
vador = { module = "com.salesforce.vador:vador", version.ref = "vador" }
vador-matchers = { module = "com.salesforce.vador:vador-matchers", version.ref = "vador" }
revoman = { module = "com.salesforce.revoman:revoman", version.ref = "revoman" }
http4k-bom = { module = "org.http4k:http4k-bom", version.ref = "http4k" }
http4k-core = { module = "org.http4k:http4k-core", version.ref = "http4k" }
http4k-client-apache = { module = "org.http4k:http4k-client-apache", version.ref = "http4k" }
http4k-format-jackson = { module = "org.http4k:http4k-format-jackson", version.ref = "http4k" }
http4k-metrics-micrometer = { module = "org.http4k:http4k-metrics-micrometer", version.ref = "http4k" }
moshix-adapters = { module = "dev.zacsweers.moshix:moshi-adapters", version.ref = "moshix" }
klaxon = { module = "com.beust:klaxon", version.ref = "klaxon" }
graal-sdk = { module = "org.graalvm.sdk:graal-sdk", version.ref = "graal" }
graal-js = { module = "org.graalvm.js:js", version.ref = "graal-js" }
immutables-value = { module = "org.immutables:value", version.ref = "immutables" }
immutables-builder = { module = "org.immutables:builder", version.ref = "immutables" }
immutables-value-annotations = { module = "org.immutables:value-annotations", version.ref = "immutables" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "apache-log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "apache-log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "apache-log4j" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
arrow-optics-ksp-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
state-machine = { module = "com.tinder.statemachine:statemachine", version.ref = "state-machine" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
rabbitmq-client = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq-client" }
spring-beans = { module = "org.springframework:spring-beans", version.ref = "spring" }
okio-jvm = { module = "com.squareup.okio:okio-jvm", version.ref = "okio" }
pprint = { module = "io.exoquery:pprint-kotlin", version.ref = "pprint" }

# Spring (version managed by spring-dependency-management)
spring-boot-starter-batch = { module = "org.springframework.boot:spring-boot-starter-batch" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-batch-test = { module = "org.springframework.batch:spring-batch-test" }

# Gradle plugins (Only declare the ones needed for buildSrc)
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-spring-gradle = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
spring-dependency-management-gradle = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version.ref = "spring-dependency-management" }
spring-boot-gradle = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kover-gradle = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kover" }
spotless-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
spotbugs-gradle = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugs" }
gradle-doctor-gradle = { module = "com.osacky.doctor:com.osacky.doctor.gradle.plugin", version.ref = "gradle-doctor" }
dependency-analysis-gradle = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependency-analysis" }

[bundles]
kotest = [
  "kotest-assertions-core",
  "kotest-property",
  "kotest-runnerJUnit5",
]
junit = ["junit-jupiter", "junit-engine"]
vador = ["vador", "vador-matchers"]
apache-log4j = ["log4j-api", "log4j-core", "log4j-slf4j2-impl"]
arrow = ["arrow-core", "arrow-optics", "arrow-fx-coroutines"]
http4k = [
  "http4k-bom",
  "http4k-core",
  "http4k-client-apache",
  "http4k-format-jackson",
  "http4k-metrics-micrometer"
]
kotlin-logging = ["kotlin-logging-jvm", "log4j-api", "log4j-core", "log4j-slf4j2-impl"]

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-gradle" }
testLogger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }
gradle-doctor = { id = "com.osacky.doctor", version.ref = "gradle-doctor" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
moshix = { id = "dev.zacsweers.moshix", version.ref = "moshix" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
kotlin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
